### ISSUE TITLE
How to use tournamenter?

### ISSUE THREAD

**Issue by trenta3** [ivanseidel/Tournamenter#3]
There is only little documentation for how to start the app and it doesn't work for me: I've installed `tournamenter` with `npm` and run `tournamenter`. The application prints the configuration parameters to the screen and then exit, without binding to the given port (which is the default 3000).

Also installng the given debian package in a docker doesn't help, this time running `tournamenter-app` does not print anything to the console and exits.

How should I do to get it started?

**Comment by ivanseidel** [comment]
Hi @trenta3 !

Thanks for reaching out.

Currently, you can install and run Tournamenter trough the Tournamenter App:
- https://github.com/TendaDigital/TournamenterApp
- http://tournamenter.tenda.digital/

Also, I'm attaching a Manual used in Brazilian Robotics Olimpiad. It's in portuguese but you can try to translate:
https://drive.google.com/file/d/0B49WoqW-RRLkWDJ2MEJFMlBLd00/view?usp=sharing

**Comment by trenta3** [comment]
Thank you for the reply, I will have a look at it!
