### ISSUE TITLE
Password Error

### ISSUE THREAD

**Issue by panicco** [ivanseidel/Tournamenter#4]
Setting a Password results in multiple requests to login function causing browser time out error.

Not sure where the issue is been looking for an hour!

`
[GET : 302] 2019-10-25T00:29:51.221Z    (14.782 ms 56b) / - ::1
[GET : 302] 2019-10-25T00:29:51.226Z    (1.022 ms 46b) /login - ::1
[GET : 302] 2019-10-25T00:29:51.232Z    (0.876 ms 56b) / - ::1
[GET : 302] 2019-10-25T00:29:51.236Z    (0.796 ms 46b) /login - ::1
[GET : 302] 2019-10-25T00:29:51.240Z    (0.792 ms 56b) / - ::1
[GET : 302] 2019-10-25T00:29:51.244Z    (0.756 ms 46b) /login - ::1
[GET : 302] 2019-10-25T00:29:51.248Z    (0.663 ms 56b) / - ::1
[GET : 302] 2019-10-25T00:29:51.251Z    (0.573 ms 46b) /login - ::1
[GET : 302] 2019-10-25T00:29:51.256Z    (0.993 ms 56b) / - ::1
[GET : 302] 2019-10-25T00:29:51.260Z    (0.448 ms 46b) /login - ::1
[GET : 302] 2019-10-25T00:29:51.263Z    (0.581 ms 56b) / - ::1
[GET : 302] 2019-10-25T00:29:51.265Z    (0.503 ms 46b) /login - ::1
[GET : 302] 2019-10-25T00:29:51.269Z    (0.620 ms 56b) / - ::1
[GET : 302] 2019-10-25T00:29:51.272Z    (0.530 ms 46b) /login - ::1
[GET : 302] 2019-10-25T00:29:51.275Z    (0.579 ms 56b) / - ::1
[GET : 302] 2019-10-25T00:29:51.278Z    (0.427 ms 46b) /login - ::1
[GET : 302] 2019-10-25T00:29:51.281Z    (0.557 ms 56b) / - ::1
[GET : 302] 2019-10-25T00:29:51.283Z    (0.403 ms 46b) /login - ::1
[GET : 302] 2019-10-25T00:29:51.286Z    (0.584 ms 56b) / - ::1
[GET : 302] 2019-10-25T00:29:51.289Z    (0.465 ms 46b) /login - ::1
`

**Comment by ivanseidel** [comment]
Hi @panicco 

can you tell me if you are using tournamenter from source (running on terminal) or running on the Tournamenter App? If on terminal, what command are you giving it to run?

Thanks

**Comment by panicco** [comment]
running via terminal. no application version

node app.js
@ivanseidel

**Comment by ivanseidel** [comment]
No env vars?

**Comment by panicco** [comment]
I passed the password into the config file. not sure how to send env vars been looking


`// General App configs
var root = path.join(__dirname, '/..')
var appUid = 'Support Force Tournament'
var appName = 'Support Force Tournament'
var appLogo = env.APP_LOGO || path.join(__dirname, '/../public/img/branding.png')
var version = package.version
var password = env.PASSWORD || 'test'`

**Comment by ivanseidel** [comment]
hi pannico, are you using windows, mac or linux?

**Comment by panicco** [comment]
Im probably being a noob. Do I pass them in like so

Node app.js -PASSWORD "test"

**Comment by ivanseidel** [comment]
ENV vars are paassed like this in any unix system:

`ENVNAME=value ENVNAME2=value2 node app.js`

**Comment by ivanseidel** [comment]
in your case, `PASSWORD=1234 node app`

**Comment by panicco** [comment]
NVM I pulled a big noob here. I'll mark close after I test lol

**Comment by ivanseidel** [comment]
Why dont you use the TournamenterApp? It's UI will help you do that without using the terminal

**Comment by panicco** [comment]
I need to run the source version for web panel integration.

so now its passing the password in but not site says wrong password??? lol

**Comment by panicco** [comment]
Looks Like passing numerical passwords causes error with password entry

**Comment by ivanseidel** [comment]
Try like this: `PASSWORD="1234" node app`
